<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => 'О проекте',
    'Change password' => 'Изменить пароль',
    'Check your e-mail and press link to continue' => 'Проверьте почту и проследуйте по ссылке в письме для продолжения',
    'Check your email for confirmation link' => 'Проверьте эл. почту для продолжения регистрации',
    'Choose password:' => 'Придумайте пароль:',
    'E-mail must be filled on signup page' => 'Адрес эл. почты нужно указать на странице Signup',
    'E-mail:' => 'Адрес эл. почты:',
    'Enter new password:' => 'Введите новый пароль:',
    'Go to login page' => 'На страницу входа',
    'Invalid e-mail address' => 'Указан не правильный адрес эл. почты',
    'Login' => 'Войти',
    'Logout' => 'Выход',
    'New password:' => 'Новый пароль:',
    'Next' => 'Дальше »',
    'Password changed. You can use it for login' => 'Пароль изменён. Вы можете его использовать для входа',
    'Password:' => 'Пароль:',
    'Profile' => 'Профиль',
    'Register' => 'Зарегистрироваться',
    'Remember me' => 'Запомнить меня',
    'Reset password' => 'Сбросить пароль',
    'Set new password' => 'Установить новый пароль',
    'Settings' => 'Настройки',
    'Sign up' => 'Регистрация',
    'Sign up confirm' => 'Требуется подтверждение эл. почты',
    'Some info' => 'Пару слов',
    'This Nickname already taken, choose another one.' => 'Это имя уже занято, выберите другое.',
    'This e-mail already registered' => 'Этот адрес эл. почты уже зарегистрирован',
    'User menu' => 'Меню пользователя',
    'VideoSchool' => 'ВидеоШкола',
    'Welcome!' => 'Добро пожаловать!',
    'Your Nickname:' => 'Выберите уникальное имя:',
    'Your current password:' => 'Текущий пароль:',
    '{attribute} must be filled' => '{attribute} необходимо указать',
];
