<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Change password' => 'Изменить пароль',
    'Complete Registration' => 'Завершение регистрации',
    'About' => 'О проекте',
    'Check your email for confirmation link' => 'Проверьте эл. почту для продолжения регистрации',
    'Choose password:' => 'Придумайте пароль:',
    'E-mail must be filled on signup page' => 'Адрес эл. почты нужно указать на странице Signup',
    'E-mail:' => 'Адрес эл. почты:',
    'Invalid e-mail address' => 'Указан не правильный адрес эл. почты',
    'Login' => 'Войти',
    'Logout' => 'Выход',
    'Next' => 'Дальше »',
    'Password:' => 'Пароль:',
    'Profile' => 'Профиль',
    'Register' => 'Зарегистрироваться',
    'Remember me' => 'Запомнить меня',
    'Settings' => 'Настройки',
    'Sign up' => 'Регистрация',
    'Sign up confirm' => 'Требуется подтверждение эл. почты',
    'Some info' => 'Пару слов',
    'This Nickname already taken, choose another one.' => 'Это имя уже занято, выберите другое.',
    'This e-mail already registered' => 'Этот адрес эл. почты уже зарегистрирован',
    'VideoSchool' => 'ВидеоШкола',
    'Welcome!' => 'Добро пожаловать!',
    'Your Nickname:' => 'Выберите уникальное имя:',
    '{attribute} must be filled' => '{attribute} необходимо указать',
];
