<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => '',
    'Change password' => '',
    'Check your e-mail and press link to continue' => '',
    'Check your email for confirmation link' => '',
    'Choose password:' => '',
    'E-mail must be filled on signup page' => '',
    'E-mail:' => '',
    'Enter new password:' => '',
    'Go to login page' => '',
    'Invalid e-mail address' => '',
    'Login' => '',
    'Logout' => '',
    'New password:' => '',
    'Password changed. You can use it for login' => '',
    'Password:' => '',
    'Profile' => '',
    'Register' => '',
    'Remember me' => '',
    'Reset password' => '',
    'Set new password' => '',
    'Settings' => '',
    'Sign up' => '',
    'Sign up confirm' => '',
    'Some info' => '',
    'This Nickname already taken, choose another one.' => '',
    'This e-mail already registered' => '',
    'User menu' => '',
    'VideoSchool' => '',
    'Welcome!' => '',
    'Your Nickname:' => '',
    'Your current password:' => '',
    '{attribute} must be filled' => '',
    'Next' => 'Next »',
];
